nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  "@storybook/addon-actions@*":
    dependencies:
      react-dom: "^16"
      regenerator-runtime: "*"
  "@storybook/addon-knobs@*":
    dependencies:
      react-dom: "^16"
      regenerator-runtime: "*"
  "@storybook/addons@*":
    dependencies:
      regenerator-runtime: "*"
  "@storybook/api@*":
    dependencies:
      react-dom: "^16"
  "react-dev-utils@*":
    dependencies:
      typescript: "*"
      webpack: "^4"
  "react-docgen-typescript-loader@*":
    dependencies:
      webpack: "^4"
